---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170809213747"
editor:
  name: "AddTravisWebhookEditor"
  group: "atomist"
  artifact: "enrollment-rugs"
  version: "0.3.31"
  origin:
    repo: "git@github.com:atomisthq/enrollment-rugs"
    branch: "master"
    sha: "0f29ff9"
  parameters:
    - "atomistWebhookUrl": "https://webhook.atomist.com/atomist/travis"

